camping-trip-rails/config/routes.rb
Rails.application.routes.draw do
  resources :campsites, only: [:index]
  resources :campers, only: [:index]
  resources :supplies, only: [:index]

  resources :campsites, only: [:show] do
    resources :campers, only: [:index]
  end

  resources :campers, only: [:show] do
    resources :supplies, only: [:index]
  end
end

camping-trip-rails/app/models/camper.rb
class Camper < ActiveRecord::Base
  belongs_to :campsite
  has_many :supplies
end

camping-trip-rails/app/models/campsite.rb
class Campsite < ActiveRecord::Base
  has_many :campers
end

camping-trip-rails/app/models/supply.rb
class Supply < ActiveRecord::Base
  belongs_to :camper
end

camping-trip-rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

camping-trip-rails/app/controllers/campers_controller.rb
class CampersController < ApplicationController

  def index
    if params[:campsite_id].nil?
      @title = "All Campers:"
      @campers = Camper.all
    else
      campsite = Campsite.find(params[:campsite_id])
      @title = "Campers bunking in #{campsite.name}"
      @campers = campsite.campers
    end
  end
end

camping-trip-rails/app/controllers/campsites_controller.rb
class CampsitesController < ApplicationController

  def index
    @title = "All Campsites:"
    @campsites = Campsite.all
  end

  def show
    @title = "Campsite:"
    @campsite = Campsite.where(params[:campsite_id])
  end
end

camping-trip-rails/app/controllers/supplies_controller.rb
class SuppliesController < ApplicationController
  def index
    if params[:camper_id].nil?
      @title = "All Supplies:"
      @supplies = Supply.all
    else
      camper = Camper.find(params[:camper_id])
      @title = "Supplies Brought by #{camper.name}"
      @supplies = camper.supplies
    end
  end
end

camping-trip-rails/app/helpers/application_helper.rb
module ApplicationHelper
end

camping-trip-rails/app/views/campers/index.html.erb
<h1> <%= @title %> </h2>

<ul>
  <% @campers.each do |camper| %>
    <l1> <%= link_to camper.name, camper_supplies_path(camper.id)  %> </li>
  <% end %>
</ul>

camping-trip-rails/app/views/campsites/index.html.erb
<h1> <%= @title %> </h2>

<ul>
  <% @campsites.each do |campsite| %>
    <l1> <%= link_to campsite.name, campsite_campers_path(campsite.id) %> </li>
  <% end %>
</ul>

camping-trip-rails/app/views/campsites/show.html.erb
<h1> <%= @title %> </h2>

  <%= @campsite.name %>

camping-trip-rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CampingTripRails</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

camping-trip-rails/app/views/supplies/index.html.erb
<h1> <%= @title %> </h2>

<ul>
  <% @supplies.each do |supply| %>
    <l1> <%= supply.name %> 
  <% end %>
</ul>